### ISSUE TITLE
Make crd service socket path configurable

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/openclarity#924]
Looks like in RKE2 the socket is located at `/run/k3s/containerd/containerd.sock` https://docs.rke2.io/reference/cli_tools#containerd while OpenClarity expects the socket to be located at `/var/run/containerd/containerd.sock` https://github.com/openclarity/openclarity/blob/main/containerruntimediscovery/server/containerd/discoverer.go#L46.

We need to make the socket address configurable to sort out this issue.

_Originally posted by @paralta in https://github.com/openclarity/openclarity/issues/913#issuecomment-2464119476_

**Comment by ramizpolic** [comment]
cri-dockerd https://github.com/kubernetes-sigs/cri-tools/issues/868

**Comment by magikmw** [comment]
Hi, I'm not sure if this is fixed. I'm doing my best making sure the helm chart is updated to 1.1.2 and the variable is defined as found in the linked PR, but I still have crashloops for discoverers and this in logs for them:

```
time="2025-01-16T14:34:39Z" level=warning msg="The docker discoverer is not ready. Skipping..." app=openclarity
Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
```

`helm get values --all` shows there's env variable set in the container with `/run/k3s/containerd/containerd.sock`

Let me know how I can help.

**Comment by ramizpolic** [comment]
@magikmw could you check if the pulled image version is correct? maybe pin the discoverer version to v1.1.2 in the helm chart. i dont know if thats the case, but it may have not pulled the latest released image based on the description here. if not, please share more details on versioning here

**Comment by magikmw** [comment]
I've checked the resultant pods for image hashes, they point to 1.1.2 release.

**Comment by potter06** [comment]
> Hi, I'm not sure if this is fixed. I'm doing my best making sure the helm chart is updated to 1.1.2 and the variable is defined as found in the linked PR, but I still have crashloops for discoverers and this in logs for them:
> 
> ```
> time="2025-01-16T14:34:39Z" level=warning msg="The docker discoverer is not ready. Skipping..." app=openclarity
> Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
> failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
> Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
> failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
> ```
> 
> `helm get values --all` shows there's env variable set in the container with `/run/k3s/containerd/containerd.sock`
> 
> Let me know how I can help.

had the same issue,
Resolved using `kubectl set env daemonset/openclarity-cr-discovery-server -n <your-namespace> CONTAINERD_SOCK_ADDRESS=/run/k3s/containerd/containerd.sock` but I got only 1 pod out of 4 working (I have 4 Nodes)

**Comment by nymo** [comment]
> > Hi, I'm not sure if this is fixed. I'm doing my best making sure the helm chart is updated to 1.1.2 and the variable is defined as found in the linked PR, but I still have crashloops for discoverers and this in logs for them:
> > ```
> > time="2025-01-16T14:34:39Z" level=warning msg="The docker discoverer is not ready. Skipping..." app=openclarity
> > Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
> > failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
> > Error: unable to create discoverer: failed to create containerd discoverer: failed to create containerd client: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///var/run/containerd/containerd.sock: timeout"
> > failed to create crio discoverer: failed to create CRIO runtime service client: validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/crio/crio.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/crio/crio.sock: connect: no such file or directory"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `helm get values --all` shows there's env variable set in the container with `/run/k3s/containerd/containerd.sock`
> > Let me know how I can help.
> 
> had the same issue, Resolved using `kubectl set env daemonset/openclarity-cr-discovery-server -n <your-namespace> CONTAINERD_SOCK_ADDRESS=/run/k3s/containerd/containerd.sock` but I got only 1 pod out of 4 working (I have 4 Nodes)

Tried it aswell with the ENV var but the discoverer is still crashing because the mount point is missing. I think this should be working when https://github.com/openclarity/openclarity/pull/983 is being merged.

**Comment by ramizpolic** [comment]
Ongoing work to resolve this:
- https://github.com/openclarity/openclarity/pull/980
- https://github.com/openclarity/openclarity/pull/983

**Comment by ramizpolic** [comment]
Done with previous PRs, will be available in the next release

**Comment by magikmw** [comment]
I've updated, fixed the values to use the new configuration, and the errors stay the same.

I wonder, does this code work as it should? I'm not fluent enough in Go to spot any obvious mistakes.
https://github.com/openclarity/openclarity/blob/9730e3f55f7392855ed8dea52f804119a240d290/containerruntimediscovery/server/containerd/discoverer.go#L55-L60

It appears the envvar is set in the deamonset/pods but the application does not use it. It keeps trying the default value.

Issue I'm having doesn't even touch the mount paths, whatever I set them to, the application is trying for `/var/run/containerd/containerd.sock`. Mounted or not.
